### Data Collection

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as skl
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,r2_score

In [27]:
pv=pd.read_excel("C:\\Users\\Lenovo\\Downloads\\Project Evaluation.xlsx")

,Company,Enterprices values ($B),Date Joined,Country,City,Industry,Year,Revenue(M),Net_Income(m)
0,0x,1.05,2022-04-26,United States,San Francisco,Fintech,1961.0,894.0,794.0
1,1047 Games,1.50,2021-09-14,United States,Zephyr Cove,Internet software & services,1970.0,661.0,561.0
2,1KMXC,1.00,2021-08-30,China,Hangzhou,Hardware,1996.0,864.0,764.0
3,1Password,6.80,2021-07-08,Canada,Toronto,Cybersecurity,2009.0,467.0,367.0
4,4Paradigm,2.00,2018-12-19,China,Beijing,Artificial intelligence,1986.0,875.0,775.0
...,...,...,...,...,...,...,...,...,...
1181,ZongMu Technology,11.40,2021-06-03,China,Shanghai,Auto & transportation,2011.0,674.0,574.0
1182,Zopa,1.00,2021-10-19,United Kingdom,London,Fintech,1987.0,826.0,726.0
1183,Zume,2.25,2018-11-01,United States,Mountain View,Consumer & retail,NaN,NaN,NaN
1184,Zuoyebang,3.00,2018-07-18,China,Beijing,Edtech,NaN,NaN,NaN
1185,Zwift,1.00,2020-09-16,United States,Long Beach,E-commerce & direct-to-consumer,NaN,NaN,NaN

In [29]:
pv.isnull().sum()

Company                    0
Enterprices values ($B)    0
Date Joined                0
Country                    0
City                       0
Industry                   0
Year                       3
 Revenue(M)                3
Net_Income(m)              3
dtype: int64

In [31]:
pv.dropna(inplace =True)

In [33]:
pv.isnull().sum()

Company                    0
Enterprices values ($B)    0
Date Joined                0
Country                    0
City                       0
Industry                   0
Year                       0
 Revenue(M)                0
Net_Income(m)              0
dtype: int64

In [35]:
pv.columns

Index(['Company', 'Enterprices values ($B)', 'Date Joined', 'Country', 'City',
       'Industry', 'Year', ' Revenue(M) ', 'Net_Income(m)'],
      dtype='object')

In [37]:
pv.rename({'CityÂ':'City'}, inplace =True)

In [39]:
pv.columns

Index(['Company', 'Enterprices values ($B)', 'Date Joined', 'Country', 'City',
       'Industry', 'Year', ' Revenue(M) ', 'Net_Income(m)'],
      dtype='object')

In [42]:
pv.head

<bound method NDFrame.head of                 Company  Enterprices values ($B) Date Joined         Country  \
0                    0x                     1.05  2022-04-26   United States
1            1047 Games                     1.50  2021-09-14   United States
2                 1KMXC                     1.00  2021-08-30           China
3             1Password                     6.80  2021-07-08          Canada
4             4Paradigm                     2.00  2018-12-19           China
...                 ...                      ...         ...             ...
1178            Zipline                     2.80  2019-05-20   United States
1179             Ziroom                     6.60  2018-01-17           China
1180             ZocDoc                     1.80  2015-08-20   United States
1181  ZongMu Technology                    11.40  2021-06-03           China
1182               Zopa                     1.00  2021-10-19  United Kingdom

                     City                             Industry    Year  \
0           San Francisco                              Fintech  1961.0
1             Zephyr Cove         Internet software & services  1970.0
2                Hangzhou                             Hardware  1996.0
3                 Toronto                        Cybersecurity  2009.0
4                 Beijing              Artificial intelligence  1986.0
...                   ...                                  ...     ...
1178  South San Francisco  Supply chain, logistics, & delivery  1964.0
1179              Beijing      E-commerce & direct-to-consumer  1988.0
1180             New York                               Health  1996.0
1181             Shanghai                Auto & transportation  2011.0
1182               London                              Fintech  1987.0

       Revenue(M)   Net_Income(m)
0            894.0          794.0
1            661.0          561.0
2            864.0          764.0
3            467.0          367.0
4            875.0          775.0
...            ...            ...
1178         841.0          741.0
1179         829.0          729.0
1180         618.0          518.0
1181         674.0          574.0
1182         826.0          726.0

[1183 rows x 9 columns]>

In [44]:
pv.dropna

<bound method DataFrame.dropna of                 Company  Enterprices values ($B) Date Joined         Country  \
0                    0x                     1.05  2022-04-26   United States
1            1047 Games                     1.50  2021-09-14   United States
2                 1KMXC                     1.00  2021-08-30           China
3             1Password                     6.80  2021-07-08          Canada
4             4Paradigm                     2.00  2018-12-19           China
...                 ...                      ...         ...             ...
1178            Zipline                     2.80  2019-05-20   United States
1179             Ziroom                     6.60  2018-01-17           China
1180             ZocDoc                     1.80  2015-08-20   United States
1181  ZongMu Technology                    11.40  2021-06-03           China
1182               Zopa                     1.00  2021-10-19  United Kingdom

                     City                             Industry    Year  \
0           San Francisco                              Fintech  1961.0
1             Zephyr Cove         Internet software & services  1970.0
2                Hangzhou                             Hardware  1996.0
3                 Toronto                        Cybersecurity  2009.0
4                 Beijing              Artificial intelligence  1986.0
...                   ...                                  ...     ...
1178  South San Francisco  Supply chain, logistics, & delivery  1964.0
1179              Beijing      E-commerce & direct-to-consumer  1988.0
1180             New York                               Health  1996.0
1181             Shanghai                Auto & transportation  2011.0
1182               London                              Fintech  1987.0

       Revenue(M)   Net_Income(m)
0            894.0          794.0
1            661.0          561.0
2            864.0          764.0
3            467.0          367.0
4            875.0          775.0
...            ...            ...
1178         841.0          741.0
1179         829.0          729.0
1180         618.0          518.0
1181         674.0          574.0
1182         826.0          726.0

[1183 rows x 9 columns]>

In [46]:
pv_dummie =pd.get_dummies(pv,drop_first=True)

In [48]:
pv_dummie

,Enterprices values ($B),Date Joined,Year,Revenue(M),Net_Income(m),Company_1047 Games,Company_1KMXC,Company_1Password,Company_4Paradigm,Company_56PINGTAI,...,"Industry_Sequoia Capital China, ING, Alibaba Entrepreneurs Fund","Industry_Sequoia Capital China, Shunwei Capital Partners, Qualgro","Industry_Sequoia Capital, Thoma Bravo, Softbank","Industry_SingTel Innov8, Alpha JWC Ventures, Golden Gate Ventures","Industry_Supply chain, logistics, & delivery","Industry_Temasek, Guggenheim Investments, Qatar Investment Authority","Industry_Tiger Global Management, Tiger Brokers, DCM Ventures",Industry_Travel,"Industry_Vertex Ventures SE Asia, Global Founders Capital, Visa Ventures","Industry_Vision Plus Capital, GSR Ventures, ZhenFund"
0,1.05,2022-04-26,1961.0,894.0,794.0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1.50,2021-09-14,1970.0,661.0,561.0,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,1.00,2021-08-30,1996.0,864.0,764.0,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,6.80,2021-07-08,2009.0,467.0,367.0,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,2.00,2018-12-19,1986.0,875.0,775.0,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1178,2.80,2019-05-20,1964.0,841.0,741.0,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
1179,6.60,2018-01-17,1988.0,829.0,729.0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1180,1.80,2015-08-20,1996.0,618.0,518.0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1181,11.40,2021-06-03,2011.0,674.0,574.0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1182,1.00,2021-10-19,1987.0,826.0,726.0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [60]:
X=pv.drop("Enterprices values ($B)",axis=1)
y=pv['Enterprices values ($B)']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) 
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

sns.histplot(y, kde=True)
plt.title('Distribution of Enterprise Value')
plt.show()
plt.figure(figsize=(10, 8))
sns.heatmap(data.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

ValueError: could not convert string to float: 'MessageBird'

In [62]:
lr_model = LinearRegression()
# Train the model on the training data
lr_model.fit(X_train, y_train)
# Make predictions on the testing data
y_pred_lr = lr_model.predict(X_test)
# Initialize the Random Forest Regressor model
rf_model = RandomForestRegressor(random_state=42)
# Train the model on the training data
rf_model.fit(X_train, y_train)
# Make predictions on the testing data
y_pred_rf = rf_model.predict(X_test)

ValueError: could not convert string to float: 'MessageBird'

In [64]:
mse_lr = mean_squared_error(y_test, y_pred_lr)
r2_lr = r2_score(y_test, y_pred_lr)
print(f'Linear Regression Mean Squared Error: {mse_lr}')
print(f'Linear Regression R-squared: {r2_lr}')
# Evaluate the Random Forest model's performance
mse_rf = mean_squared_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)
print(f'Random Forest Mean Squared Error: {mse_rf}')
print(f'Random Forest R-squared: {r2_rf}')

NameError: name 'y_pred_lr' is not defined

In [66]:
from sklearn.model_selection import GridSearchCV
# Define the parameter grid for Random Forest
param_grid = {
'n_estimators': [100, 200, 300],
'max_depth': [None, 10, 20, 30],
'min_samples_split': [2, 5, 10]
}
# Perform Grid Search with cross-validation
grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid, cv=5,
n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)
# Print the best parameters and best score
print(f'Best Parameters: {grid_search.best_params_}')
print(f'Best Score: {grid_search.best_score_}')
# Train the model with the best parameters
best_rf_model = grid_search.best_estimator_
best_rf_model.fit(X_train, y_train)
# Make predictions on the testing data
y_pred_rf_optimized = best_rf_model.predict(X_test)
# Evaluate the optimized model's performance
mse_rf_optimized = mean_squared_error(y_test, y_pred_rf_optimized)
r2_rf_optimized = r2_score(y_test, y_pred_rf_optimized)
print(f'Optimized Random Forest Mean Squared Error: {mse_rf_optimized}')
print(f'Optimized Random Forest R-squared: {r2_rf_optimized}')

NameError: name 'rf_model' is not defined